upstream rails_app {
    server 127.0.0.1:3000;
}

server {
    listen 80;
    server_name _;

    root /var/www/aws-rails-cloud-deploy/public;

    access_log /var/log/nginx/aws-rails-access.log;
    error_log  /var/log/nginx/aws-rails-error.log;

    location /assets/ {
        expires max;
        add_header Cache-Control public;
        gzip_static on;
    }

    location / {
        try_files $uri @rails;
    }

    location @rails {
        proxy_pass http://rails_app;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect   off;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}
